services:
  db:
    image: postgres:16-alpine
    container_name: db-quick-order
    platform: linux/amd64
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      timeout: 10s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
