@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzI4MDU2NjksImV4cCI6MTczNDUzOTM3NTEwMSwiaXNzIjoiYWNjZXNzLXRva2VuIiwic3ViIjoiY20zeW9jajZpMDAwMXp2M3ptazBseXU0biJ9.LJ4_UZn19ebdyhH38bsbaEC1pX87uS-wgOKVqBBaRSw
@fingerPrint = 1234567890

### Create order
POST {{baseUrl}}/orders
Content-Type: multipart/form-data
Authorization: Bearer {{token}}
X-Fingerprint: {{fingerPrint}}

# image: file
# description: string
# salePrice: number
# receivedPrice: number
// TODO: add body params

### Get all orders
GET {{baseUrl}}/orders
Authorization: Bearer {{token}}
X-Fingerprint: {{fingerPrint}}

### Get order by id
GET {{baseUrl}}/orders/cm41cewvf0005qh9ecgmt9vnb
Authorization: Bearer {{token}}
X-Fingerprint: {{fingerPrint}}

### Update order by id
PATCH {{baseUrl}}/orders/cm41cewvf0005qh9ecgmt9vnb
Content-Type: multipart/form-data
Authorization: Bearer {{token}}
X-Fingerprint: {{fingerPrint}}

# image: file
# description: string
# salePrice: number
# receivedPrice: number
// TODO: add body params

### Delete order by id
DELETE {{baseUrl}}/orders/cm41cewvf0005qh9ecgmt9vnb
Authorization: Bearer {{token}}
X-Fingerprint: {{fingerPrint}}
