@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzI2NTY0NjAsImV4cCI6MTczNDM5MDAxNzM3MCwiaXNzIjoiYWNjZXNzLXRva2VuIiwic3ViIjoiY20zeW9jajZpMDAwMXp2M3ptazBseXU0biJ9.ZX2hFpQe2qqGMREpn6R83GaAntGhLJrg3qmvd2P0HnI

### Create order
POST {{baseUrl}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "image": "https://www.google.com",
  "description": "Order description",
  "salePrice": 100.00,
  "receivedPrice": 100.00
}

### Get all orders
GET {{baseUrl}}/orders
Authorization: Bearer {{token}}
X-Fingerprint: 1234567890

