@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzI3OTk5NDYsImV4cCI6MTczNDUzMzY0NjQ0NCwiaXNzIjoiYWNjZXNzLXRva2VuIiwic3ViIjoiY20zeW9jajZpMDAwMXp2M3ptazBseXU0biJ9.vVtTbJ0PLbBoJ9-t7vWOQwh1y8KuG9Wn_vmONmbyNFM
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzI2NTg0ODIsImV4cCI6MTczNDk5NTk0MDkyMCwiaXNzIjoicmVmcmVzaC10b2tlbiIsInN1YiI6ImNtM3lvY2o2aTAwMDF6djN6bWswbHl1NG4ifQ.4Z4ce43WWPvYjSWGZIQyCjhniefZBuPwrc7UcXp2nLQ
@fingerPrint = 1234567890

### Register
POST {{baseUrl}}/auth/register
Authorization: Bearer {{token}}
Content-Type: application/json
X-Fingerprint: {{fingerPrint}}

{
  "email": "user02@quickorder.com",
  "password": "hashed-password",
  "role": "EMPLOYEE"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json
X-Fingerprint: {{fingerPrint}}

{
  "email": "admin@quickorder.com",
  "password": "Senha#123"
}

### Refresh
POST {{baseUrl}}/auth/refresh
X-Refresh-Token: {{refresh_token}}
X-Fingerprint: {{fingerPrint}}

### Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{token}}
X-Fingerprint: {{fingerPrint}}

### Me
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}
X-Fingerprint: {{fingerPrint}}

### Forgot Password
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "admin@quickorder.com"
}

### Reset Password
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
X-Fingerprint: {{fingerPrint}}

{
  "email": "admin@quickorder.com",
  "code": "123456",
  "password": "Senha#123"
}
